export const types = {
  FETCH_ACTION_MOVIES: 'FETCH_ACTION_MOVIES',
  FETCH_ADVENTURE_MOVIES: 'FETCH_ADVENTURE_MOVIES',
  FETCH_SCIFI_MOVIES: 'FETCH_SCIFI_MOVIES',
  FETCH_ANIMATION_MOVIES: 'FETCH_ANIMATION_MOVIES',
  FETCH_DOCUMENTARY_MOVIES: 'FETCH_DOCUMENTARY_MOVIES',
  FETCH_SELECTED_MOVIE: 'FETCH_SELECTED_MOVIE',
  FETCH_DETAILS_ERROR: 'FETCH_DETAILS_ERROR',
  SEARCH_MOVIE: 'SEARCH_MOVIE',
};
